fn main() {
    // Embeds the SHA-256 fingerprint of the code-signing certificate so the
    // app can refuse to spawn a sidecar signed by anyone else. Generated by
    // scripts/generate-signing-cert.ps1; without it the check is disabled.
    println!("cargo:rerun-if-changed=signing/cert-fingerprint.txt");
    match std::fs::read_to_string("signing/cert-fingerprint.txt") {
        Ok(fingerprint) => println!(
            "cargo:rustc-env=PONTUALL_SIDECAR_CERT_SHA256={}",
            fingerprint.trim()
        ),
        Err(_) => println!(
            "cargo:warning=signing/cert-fingerprint.txt not found; sidecar signature \
             verification is DISABLED in this build. Run scripts/generate-signing-cert.ps1."
        ),
    }
    tauri_build::build()
}
